### ISSUE TITLE
failed to deploy pipeline

### ISSUE THREAD

**Issue by mohammadne** [okteto/pipeline#14]
hi

after running `okteto/pipeline@latest` I will get this error:
```
x  failed to deploy pipeline: failed to deploy okteto pipeline
```

I have specified my pipeline in `.okteto/okteto-pipeline.yml`

[link to actual repo](https://github.com/mohammadne/bookman)

**Comment by rberrelleza** [comment]
Thanks for raising the issue. Could it be possible to let us know what was the error reported in the preview environment in Okteto? You can see it by clicking on the URL of the preview env that's added as a comment.

**Comment by mohammadne** [comment]
it was due to the configmap and the name referenced as a configmap mount in the deployment manifest are not matching.
