### ISSUE TITLE
customize path to pipeline path

### ISSUE THREAD

**Issue by mohammadne** [okteto/pipeline#15]
currently, what I have is a file in `.okteto/okteto-pipeline.yml`
but what I want is to have multiple seperate pipelines to be run like : 

``` 
.okteto/custom-pipeline-1.yml
.okteto/custom-pipeline-2.yml
```

the reason why I'm doing this is because I have a modular-monolithic application
and I want to have multiple and seperate pipelines

as you can see in this [link](https://github.com/mohammadne/bookman), each service has its deployment and with current approach each service will trigger all services deployment which is completely wrong. my idea is to have something like github workflows which we can define multiple workflows.

thanks !

**Comment by mohammadne** [comment]
[related pull-request](https://github.com/okteto/pipeline/pull/16)

**Comment by mohammadne** [comment]
thanks for approving the pull request.

to close this issue one step is remaining and that's updating the latest release.

**Comment by mohammadne** [comment]
thanks @pchico83 for approving the pull request.

to close this issue one step is remaining and that's updating the latest release.

**Comment by pchico83** [comment]
@mohammadne we do that everytime we do an Okteto CLI release. there is one coming this week.
In the meantime, you can use `master`.
